[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.tpl.model.User[]" --]
[#-- @ftlvariable name="posts" type="ru.itmo.tpl.model.Post[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.tpl.model.User" --]
[#-- @ftlvariable name="cur_uri" type="java.lang.String" --]
